Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - info
    - debug
Style/DotPosition:
  EnforcedStyle: trailing
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Metrics/LineLength:
  Max: 120
Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Lint/HandleExceptions:
  Exclude:
    - Rakefile
